common:
  lid_topic: "/livox/lidar"
  # lid_topic: "/velodyne_points"
  imu_topic: "/livox/imu"
  # imu_topic: "/zed2/zed_node/imu/data"
  # imu_topic: "/handsfree/imu"

preprocess:
  lidar_type: 1     # lidar_type: 2     1           #1 for Livox serials LiDAR, 2 for Velodyne LiDAR, 3 for L515 LiDAR
  scan_line: 6      # scan_line: 64 #livox 6  #velodyne 64
  blind: 0.5
  point_filter_num: 3
  calib_laser: false              # true for KITTI Odometry dataset

mapping:
  down_sample_size: 0.5
  max_iteration: 3
  voxel_size: 0.5  #usedtobe 3.0 #nowcanbe0.5 #0.375
  plannar_threshold: 0.01
  max_points_size: 100
  update_size_threshold: 5
  sigma_num: 3

noise_model:
  ranging_cov: 0.02
  angle_cov: 0.1
  acc_cov_scale: 1.0
  gyr_cov_scale: 0.5

imu:
  imu_en: true
  extrinsic_T: [ 0, 0, 0 ]
  extrinsic_R: [ 1, 0, 0,
                 0, 1, 0,
                 0, 0, 1 ]

visualization:
  pub_voxel_map: true #true
  pub_voxel_map_period: 50
  pub_point_cloud: true
  dense_map_enable: false
  pub_point_cloud_skip: false             # publish one points per five points

Result:
  write_kitti_log: false
  result_path: "/home/ycj/catkin_github/src/VoxelMapPlus/Log/kitt_log.txt"
